config/routes.rb
Rails.application.routes.draw do
  resources :images
  #get 'contactus/index'
  #resources :contactus
  get "aboutus" => 'welcome#aboutus'
  get "contactus" => 'welcome#contactus'

  post "contact" => "welcome#contactus_create"
  get 'aboutus/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  #devise_for :users
  root 'welcome#index'
  #get "users/password/changepassword" => 'users#changepassword'
  devise_for :users, controllers: { registrations: 'users/registrations'}
  #get "users/password/changepassword" => 'users/passwords#changepassword'

  devise_scope :user do
    get  'users/password/changepassword', :to => 'users/registrations#changepassword'
    put  'users/password/changepassword', :to => 'users/registrations#updatepassword'
    post 'users/create_user', :to => 'users/registrations#user_add'
  end

  post "images/upload" => "images#upload"
  post "images/image_add" => "images#image_add"
  get "images/image_info/:id" => "images#image_info"
  post "contact_add" => "welcome#contact_add"
  get "image_count" => "images#image_count"

  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  #resources :gallery
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#root : "home#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def index
  end

  def aboutus
    set_tab :aboutus
  end

  def contactus
    set_tab :contactus
    @contact = Contact.new
  end

  def contactus_create
    set_tab :contactus
    @contact = Contact.new(contact_params)
    if @contact.save
      # Tell the UserMailer to send a welcome email after save
      #deliver_later async call#deliver_now
      ContactMailer.with(contact: @contact).welcome_email.deliver_later
      flash[:notice] = "We got your request, connect with you soon"
      redirect_to root_path
    else
      render 'contactus'
    end
  end

  def contact_add
    @contact = Contact.new
    @contact.name = params[:name]
    @contact.email = params[:email]
    @contact.mobile_no = params[:mobile_no]
    @contact.description = params[:description]
    respond_to do |format|
      if @contact.save
        format.json { render json: {"status":"SUCCESS","msg":"Saved successfully","status_code":200} }
      else
        format.json { render json: {"status":"ERROR","msg":@contact.errors,"status_code":500} }
      end
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :mobile_no, :description)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/aboutus.html.erb
<p>The name of current tab is <%= current_tab %>.</p>
<div class="wrapper row2">
  <div id="container" class="clear">
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <div id="about-us" class="clear">
      <!-- ####################################################################################################### -->
      <section id="about-intro" class="one_third first">
        <h2>About Maropost</h2>
        <div class="panorama">
          <%= image_tag("demo/maropost_logo.svg", size: "200x50", :alt => "rss feed") %>
        <blockquote>
          <p><span>&ldquo;</span> Maropost will be soon be introducing its latest offering – Maropost for Commerce. This new product will introduce the capability...</p>
        </blockquote>
          </section>
      <!-- ####################################################################################################### -->
      <section id="skillset" class="one_third">
        <h2> MAropost for commerce</h2>
        <p>Maropost will be soon be introducing its latest offering – Maropost for Commerce. This new product will introduce the capability to make all customer engagements transactional, increasing the conversions from marketing outreach to sale. We are excited to extend our offerings to help our customers grow their business.</p>

      </section>
      <!-- ####################################################################################################### -->
      <section id="team" class="one_third">

      </section>
      <!-- ####################################################################################################### -->
    </div>
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
    <!-- ####################################################################################################### -->
  </div>
</div>

app/views/welcome/contactus.html.erb
<%= form_with scope: :contact, url: contact_path(@contact), method: :post, local: true do |form| %>

  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@contact.errors.count, "error") %> prohibited
        this contact from being saved:
      </h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, required: true, type: 'text' %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email, required: true,type:'email'%>
  </p>

  <p>
    <%= form.label :mobile_no %><br>
    <%= form.text_field :mobile_no,required: true,type: 'number' %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description, required: true %>
  </p>

  <p>
    <%= form.submit %>
  </p>

  <iframe id="inlineFrameExample"
    title="Inline Frame Example"
    width="800"
    height="400"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBxhVTyhLStm2gAzQTuI6IzqptEYx8ooPQ&q=maropost">

<% end %>

app/views/welcome/index.html.erb
<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>