config/routes.rb
Rails.application.routes.draw do
  resources :images
  #get 'contactus/index'
  #resources :contactus
  get "aboutus" => 'welcome#aboutus'
  get "contactus" => 'welcome#contactus'

  post "contact" => "welcome#contactus_create"
  get 'aboutus/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  #devise_for :users
  root 'welcome#index'
  #get "users/password/changepassword" => 'users#changepassword'
  devise_for :users, controllers: { registrations: 'users/registrations'}
  #get "users/password/changepassword" => 'users/passwords#changepassword'

  devise_scope :user do
    get  'users/password/changepassword', :to => 'users/registrations#changepassword'
    put  'users/password/changepassword', :to => 'users/registrations#updatepassword'
    post 'users/create_user', :to => 'users/registrations#user_add'
  end

  post "images/upload" => "images#upload"
  post "images/image_add" => "images#image_add"
  get "images/image_info/:id" => "images#image_info"
  post "contact_add" => "welcome#contact_add"
  get "image_count" => "images#image_count"

  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  #resources :gallery
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#root : "home#index"
end

app/models/image.rb
require 'open-uri'
class Image < ApplicationRecord
  paginates_per 3
  validates_uniqueness_of :image_name
  has_one_attached :image

  # Bulk upload companies
  def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
          image_obj = Image.new
          image_obj.image_name = row[0]
          image_url = row[1]
          image_obj.image_url = image_url
          downloaded_image = open(image_url)
          image_obj.image.attach(io: downloaded_image  , filename: row[0])
          image_obj.save
      end
  end

  # before_save :grab_image
  #

end

app/controllers/images_controller.rb
require 'open-uri'
class ImagesController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
    def index
      # @images = Image.all
      @images = Image.all.page params[:page]
    end

    def image_count
      sleep(2)
      @image_count = Image.all.count
      respond_to do |format|
        if @image_count>0
          format.json { render json: {"count":@image_count,"status_code":200} }
        else
          format.json { render json: {"count":0,"status_code":500} }
        end
      end
    end

    def new
      @image = Image.new
    end

    def show
      @id = params[:id]
      @image = Image.find(@id)
    end

    def create
      @image = Image.new(:image_name=>params[:image][:image_name])
      if @image.save
        @image.image.attach(params[:image][:image])
        redirect_to :action => :show, :id => @image.id
      else
        render 'new'
      end
    end

    def edit
      @image = Image.find(params[:id])
    end

    def update
      @image = Image.find(params[:id])
      if params[:image][:image_name]
        if @image.update_attribute(:image_name,params[:image][:image_name])
          #redirect_to action: "index"
          flash[:notice] = "Image name updated successfully"
          redirect_to action: "index"
        else
          render 'edit'
        end
      end
    end

    def upload
      Image.import(params[:image][:file])
      flash[:notice] = "Images uploaded successfully"
      redirect_to images_path #=> or where you want
    end

    def image_info
      @image = Image.find_by_id(params[:id])
      respond_to do |format|
        if @image
          format.json { render json: {"status":"SUCCESS","msg":"Data Retrieved Successfully","status_code":200,"data":{"Image Name":@image.image_name,"Image Url":@image.image_url}} }
        else
          format.json { render json: {"status":"ERROR","msg":"Error in retrieving the data","status_code":500,"data":{} }}
        end
      end
    end

    def image_add
      @image = Image.new
      @image.image_name = params[:image_name]
      @image.image_url = params[:image_link]
      downloaded_image = open(@image.image_url)
      @image.image.attach(io: downloaded_image  , filename: @image.image_name)
      respond_to do |format|
        if @image.save
          format.json { render json: {"status":"SUCCESS","msg":"Saved successfully","status_code":200} }
        else
          format.json { render json: {"status":"ERROR","msg":@image.errors,"status_code":500} }
        end
      end
    end

    private
    def image_params
      params.require(:image).permit(:image,:image_name)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.erb
<%= image_tag(@image.image ,size: "300x400")%>

<%= form_with model: @image, remote: true do |form| %>
<p>
  <%= form.label :image_name %><br>
  <%= form.text_field :image_name %>
</p>

<p>
  <%= form.submit 'Submit', data: { disable_with: true }%>
</p>
<% end %>

app/views/images/index.html.erb
<h1>Gallery</h1>
<p id="image_count_label">Total Images Count</p>
<b><p id="image_count"></p></b>

<div class="spinner">Loading....</div>

<%= link_to 'New Image Upload', new_image_path %>
<br/>
<br/>
<%= form_for(:image, :url => {:action => 'upload'}) do |f| %>
   <div class="form-group">
      <%= f.label :file, "Upload CSV File" %>
      <%= f.file_field :file, class: 'form-control-file', required: true %>
   </div>
   <%= f.submit "Upload CSV" %>
<% end %>
<br/>
<br/>
<table>
  <tr>
    <th>Title</th>
    <th>Image</th>
    <th>Image URL</th>
    <th></th>
  </tr>

  <% @images.each do |image| %>
    <tr>
      <% cache image do %>
        <td><%= image.image_name %></td>
        <td><%= image_tag(image.image,size: "100x100") %></td>
        <td><%= image.image_url %></td>
        <td><%= link_to 'Show', image_path(image) %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
      <% end %>
    </tr>
  <% end %>

<%= paginate @images %>

</table>
<script type="text/javascript">
  $(document).ready(function() {
    $(".spinner").show();
    $("#image_count_label").css("color","yellow");

    $.ajax({
      type: "GET",
      url: "/image_count",
      success: function(data, textStatus, jqXHR){
        $("#image_count").html(data['count']);
        $(".spinner").hide();
        $("#image_count_label").css("color","green");
      },
      error: function(jqXHR, textStatus, errorThrown){
        console.log(errorThrown);
        $(".spinner").hide();
      }
  })});
</script>

app/views/images/new.html.erb
<%= form_for(:image, :url => {:action => 'create'}, :html => {:multipart => true}) do |f| %>

<% if @image.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@image.errors.count, "error") %> prohibited
      this image from being uploaded:
    </h2>
    <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= f.label :image_name %><br>
  <%= f.text_field :image_name, required: true%>
</p>
  <%= f.file_field :image %>
  <%= f.submit "Upload" %>
<% end %>

app/views/images/show.html.erb
<%= image_tag(@image.image ,size: "300x400")%>
<p><%= @image.image_name %></p>