config/routes.rb
Rails.application.routes.draw do
  resources :images
  #get 'contactus/index'
  #resources :contactus
  get "aboutus" => 'welcome#aboutus'
  get "contactus" => 'welcome#contactus'

  post "contact" => "welcome#contactus_create"
  get 'aboutus/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  #devise_for :users
  root 'welcome#index'
  #get "users/password/changepassword" => 'users#changepassword'
  devise_for :users, controllers: { registrations: 'users/registrations'}
  #get "users/password/changepassword" => 'users/passwords#changepassword'

  devise_scope :user do
    get  'users/password/changepassword', :to => 'users/registrations#changepassword'
    put  'users/password/changepassword', :to => 'users/registrations#updatepassword'
    post 'users/create_user', :to => 'users/registrations#user_add'
  end

  post "images/upload" => "images#upload"
  post "images/image_add" => "images#image_add"
  get "images/image_info/:id" => "images#image_info"
  post "contact_add" => "welcome#contact_add"
  get "image_count" => "images#image_count"

  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  #resources :gallery
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#root : "home#index"
end

app/views/layouts/_footer.html.erb
<p>©2017 Maropost Inc. All rights reserved. |
  <%= link_to 'Contact Us', contactus_path %></p>

app/views/layouts/_header.html.erb
<%= tabs_tag open_tabs: { id: 'tabs', class: 'cool' } do |tab| %>
  <%= tab.aboutus    'About Us', aboutus_path %>
  <%= tab.contactus  'Contact Us', contactus_path %>
  <%= tab.gallery    'Gallery', images_path %>
  <%= link_to 'Forgot Password', new_user_password_path %>
  <%= link_to 'Change Password', users_password_changepassword_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoassignment</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= render "layouts/footer" %>


  </body>
</html>